services:
    jupyterhub_hub:
        build: jupyterhub
        container_name: jupyterhub_hub
        hostname: jupyterhub_hub
        networks:
            - jupyterhub_network
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - CONFIGPROXY_AUTH_TOKEN
            - DOCKER_NETWORK_NAME
            - DOCKER_NOTEBOOK_IMAGE
            - JPY_SERVICE_ADMINS
            - JPY_COOKIE_SECRET
            - ACCESS_CONTROL_ORIGINS
        depends_on:
            - jupyterhub_db
            - jupyterhub_proxy
        restart: unless-stopped

    jupyterhub_db:
        image: postgres:16.2
        container_name: jupyterhub_db
        hostname: jupyterhub_db
        networks:
            - jupyterhub_network
        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
        restart: unless-stopped

    jupyterhub_proxy:
        build:
            context: configurable-http-proxy
        container_name: jupyterhub_proxy
        image: configurable-http-proxy-ssl
        hostname: jupyterhub_proxy
        networks:
            - jupyterhub_network
        ports:
            - "8000:8000"
        environment:
            - CONFIGPROXY_AUTH_TOKEN
        volumes:
            - ${SSL_DIR_PATH}:/etc/ssl/jupyter-docker-ssl
        restart: unless-stopped

networks:
    jupyterhub_network:
        name: jupyterhub_network
        # allows using an existing network stack not defined by this docker-compose file.
        # external: true